GET http://localhost:3000/api/usuarios

###

GET http://localhost:3000/api/usuarios/d


###
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "username": "test-username",
    "email": "email@test.com",
    "password": "TEST12345",
    "direccion": "Calle Do Testing 123",
    "nombre": "Testeador",
    "apellidos": "Von Testing",
    "fecha_nacimiento": "1970-01-02",
    "trusted": false
}

###

POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "username": "test-username",
    "email": "email@test.com",
    "password": "TEST12345"
}

### //PETICIONES -- PRODUCTOS --

GET http://localhost:3000/api/productos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImV4cERhdGUiOjE2NTgyMTkwMTAsImlhdCI6MTY1ODEzMjYxMH0.VivCgpwzYSV_L6XvByLd9JPDeUvQkl9BZJWd7N0W7xg

###

GET http://localhost:3000/api/productos/categoria/videojuegos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImV4cERhdGUiOjE2NTgyMTkwMTAsImlhdCI6MTY1ODEzMjYxMH0.VivCgpwzYSV_L6XvByLd9JPDeUvQkl9BZJWd7N0W7xg

###

GET http://localhost:3000/api/productos/estado/usado
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImV4cERhdGUiOjE2NTgyMTkwMTAsImlhdCI6MTY1ODEzMjYxMH0.VivCgpwzYSV_L6XvByLd9JPDeUvQkl9BZJWd7N0W7xg

###

GET http://localhost:3000/api/productos/marca/ap
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImV4cERhdGUiOjE2NTgyMTkwMTAsImlhdCI6MTY1ODEzMjYxMH0.VivCgpwzYSV_L6XvByLd9JPDeUvQkl9BZJWd7N0W7xg


###

GET http://localhost:3000/api/productos/usuario/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImV4cERhdGUiOjE2NTgyMTkwMTAsImlhdCI6MTY1ODEzMjYxMH0.VivCgpwzYSV_L6XvByLd9JPDeUvQkl9BZJWd7N0W7xg


###

GET http://localhost:3000/api/productos/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImV4cERhdGUiOjE2NTgyMTkwMTAsImlhdCI6MTY1ODEzMjYxMH0.VivCgpwzYSV_L6XvByLd9JPDeUvQkl9BZJWd7N0W7xg

###

POST http://localhost:3000/api/productos/nuevo
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImV4cERhdGUiOjE2NTgyMTkwMTAsImlhdCI6MTY1ODEzMjYxMH0.VivCgpwzYSV_L6XvByLd9JPDeUvQkl9BZJWd7N0W7xg
Content-Type: application/json

{
    "nombre": "castlevania sotn PS1",
    "categoria": "videojuegos",
    "marca": "Konami",
    "estado": "usado",
    "usuario_id": 1
}

###

DELETE  http://localhost:3000/api/productos/eliminar/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImV4cERhdGUiOjE2NTgyMTkwMTAsImlhdCI6MTY1ODEzMjYxMH0.VivCgpwzYSV_L6XvByLd9JPDeUvQkl9BZJWd7N0W7xg

###

PATCH  http://localhost:3000/api/productos/editar/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImV4cERhdGUiOjE2NTgyMTkwMTAsImlhdCI6MTY1ODEzMjYxMH0.VivCgpwzYSV_L6XvByLd9JPDeUvQkl9BZJWd7N0W7xg
Content-Type: application/json

{
    "nombre": "Kingdom Hearts 1",
    "precio": 65,
    "categoria": "videojuegos",
    "imagen": "https://i.imgur.com/b90NgSA.png",
    "marca": "SQ Soft",
    "estado": "usado"
}